### ISSUE TITLE
How does one engage a conversation with a villager?

### ISSUE THREAD

**Issue by TaarKaRaja** [Ranzeplay/saysth#13]
No villager talks when I click on them, trade, or type in chat.

**Comment by Ranzeplay** [comment]
By default, you should put a `$` sign at the beginning of your chat message.
Also, you need to set the config before using the mod.
In addition, which version are you using? mod version and game version.

**Comment by Ranzeplay** [comment]
You may refer to this link https://saysth.ranzeplay.space/docs/0.3/config and check your configurations.
If still fails, please upload game logs.
