### ISSUE TITLE
Unable to Chat With Villagers

### ISSUE THREAD

**Issue by StealthMeister1** [Ranzeplay/saysth#14]
**Describe the bug**
Unable to chat with villagers when I type in chat. Using the default prefix "$". Followed OpenAI instructions and input my API key. Didn't work. Nothing appears in chat when I try to type something. Not even my own message.

**Logs**
[latest.log](https://github.com/user-attachments/files/18237181/latest.log)

I noticed in the logs there seems to be some issues with the mod. I'm not savvy enough to know exactly what's going on though.

**Version information**
- Game version: 1.21
- Mod loader: Fabric
- OS version: Windows 10
- Mod Version: 1.0

**Additional context**

**Comment by Ranzeplay** [comment]
I noticed that the error occurred when the mod was trying to generate the personality for a new villager. Please check that there are any candidates of personality.

For instance, consider replacing `"personalities": []` in `saysth/saysth-config.json` with
```json
"personalities": [
    "decisive",
    "confident",
    "motivational",
    "analytical",
    "introspective",
    "creative",
    "empathetic",
    "supportive",
    "nurturing",
    "spontaneous",
    "curious",
    "energetic",
    "diplomatic",
    "harmonious",
    "patient",
    "imaginative",
    "visionary",
    "resourceful",
    "practical",
    "down-to-earth",
    "reliable",
    "charismatic",
    "expressive",
    "entertaining",
    "knowledgeable",
    "curious",
    "detail-oriented",
    "ambitious",
    "inspirational",
    "forward-thinking"
]
```
and add a comma after that.

See also: https://saysth.ranzeplay.space/docs/config/main

**Comment by Ranzeplay** [comment]
So the final config would be like this:
```json
{  
  "personalities": [
    "decisive",
    "confident",
    "motivational",
    "analytical",
    "introspective",
    "creative",
    "empathetic",
    "supportive",
    "nurturing",
    "spontaneous",
    "curious",
    "energetic",
    "diplomatic",
    "harmonious",
    "patient",
    "imaginative",
    "visionary",
    "resourceful",
    "practical",
    "down-to-earth",
    "reliable",
    "charismatic",
    "expressive",
    "entertaining",
    "knowledgeable",
    "curious",
    "detail-oriented",
    "ambitious",
    "inspirational",
    "forward-thinking"
  ],  
  "nameCandidates": [],   
  "conclusionMessageLimit": 10,  
  "villagerChatPrefix": "$",  
  "useExistingVillagerName": true,  
  "showTimeConsumption": false,
  "timeoutSeconds": 10,
  "apiConfigPlatform": "cloudflare"  
}  
```
Also don't forget to fill in the name list :)

**Comment by StealthMeister1** [comment]
Names are generating when I use the prefix... But I am not getting a response even when directly addressing them.
[latest.log](https://github.com/user-attachments/files/18237397/latest.log)

**Comment by Ranzeplay** [comment]
I see. It is my fault that I didn't consider all the exceptions. I'll upload a new version to identify the real issue more easily.
Thank you for your feedback and support!

**Comment by StealthMeister1** [comment]
And thank you for the timely responses! I'm quite pleasantly surprised that you got back to me so quickly.

**Comment by StealthMeister1** [comment]
Tried.... Now it's saying I don't have an API key when I clearly do.

[latest.log](https://github.com/user-attachments/files/18237994/latest.log)

**Comment by StealthMeister1** [comment]
I redid the api config as it showed and now this comes up.
[latest.log](https://github.com/user-attachments/files/18238054/latest.log)

I changed "authCredentials" to "Authorization": Bearer

Then followed that up with my key.

**Comment by Ranzeplay** [comment]
Okay, try to change `"authCredentials": "xxx-xxx-xxx",` to `"authCredentials": "Bearer xxx-xxx-xxx",`

**Comment by StealthMeister1** [comment]
Apologies for the delay. I went to bed.

Now it says "The model gpt-4 does not exist or you do not have access to it."

**Comment by StealthMeister1** [comment]
I should have access to this. I even pay for ChatGPT for more advanced versions.

**Comment by StealthMeister1** [comment]
I actually fixed that problem myself! But now I've run into yet ANOTHER problem.
[latest.log](https://github.com/user-attachments/files/18242834/latest.log)

**Comment by Ranzeplay** [comment]
I'm working on it, seems like compatibility issue.

**Comment by Ranzeplay** [comment]
Try [this](https://github.com/Ranzeplay/saysth/actions/runs/12489597312/artifacts/2360793139) mod file built just now

**Comment by StealthMeister1** [comment]
Oh my goodness. It just now told me you responded even though it shows that you responded yesterday. That's odd. I'm so sorry.

It doesn't appear to have worked. I am now getting this. The names won't even load now. It seems to be another compatibility error.
[latest.log](https://github.com/user-attachments/files/18249638/latest.log)

**Comment by Ranzeplay** [comment]
That's too strange. I'll continue to working on it tonight.

**Comment by Ranzeplay** [comment]
I reproduced your issue with ***[this](https://github.com/Ranzeplay/saysth/actions/runs/12479374317/artifacts/2358697026)*** archive, which was mentioned here:
> Could you please download a zip archive from [here](https://github.com/Ranzeplay/saysth/actions/runs/12479374317/artifacts/2358697026)? You may check that it is an artifact of my GitHub Actions workflow. It is safe since all the details are public in this repo. Use `saysth-fabric-1.0.jar` inside to replace the original mod file, do what you did before again, and then upload the log file. Thank you :)

But I could not reproduce the issue in ***[this](https://github.com/Ranzeplay/saysth/actions/runs/12489597312/artifacts/2360793139)*** archive, everything seems fine.
> Try [this](https://github.com/Ranzeplay/saysth/actions/runs/12489597312/artifacts/2360793139) mod file built just now

**Comment by StealthMeister1** [comment]
It's still not working.
[latest.log](https://github.com/user-attachments/files/18254292/latest.log)

Is it a compatibility error regarding another mod I have installed...?

**Comment by Ranzeplay** [comment]
It could be. If want to step further, please send me the modpack you are using.

**Comment by StealthMeister1** [comment]
Here you are.
[1.21 Fabric.zip](https://github.com/user-attachments/files/18257967/1.21.Fabric.zip)

**Comment by Ranzeplay** [comment]
Highly possible that there are some compatibility issues.

**Comment by Ranzeplay** [comment]
Ok, I think I've figured it out.
You should not put all 3 jars in the zip archive to `mods` folder. Instead, remove the following:
- `saysth-fabric-1.0-dev-shadow.jar`
- `saysth-fabric-1.0-sources.jar`

**Comment by StealthMeister1** [comment]
Still not working.
[latest.log](https://github.com/user-attachments/files/18268696/latest.log)

**Comment by Ranzeplay** [comment]
I repacked the modpack, which works on my computer. If still not working on your side, then I may ave no idea.

Link: [1.21.Fabric.zip](https://github.com/user-attachments/files/18269419/1.21.Fabric.zip)

**Comment by StealthMeister1** [comment]
Well the last time I did it. I didn't see any real problem in the log. Names came up again, but the villagers just didn't chat back.

**Comment by Ranzeplay** [comment]
Noooooo

**Comment by StealthMeister1** [comment]
Don't worry. I'm just now starting up that last pack you sent me.

**Comment by StealthMeister1** [comment]
HOLY SHIT IT WORKED

**Comment by Ranzeplay** [comment]
Niiiiice

**Comment by StealthMeister1** [comment]
Well...  That was a hell of a lot of issues to go through. Did no one else have these issues?

**Comment by Ranzeplay** [comment]
No one sent me the feedback before.
I'll update the mod on Modrinth now.

**Comment by Ranzeplay** [comment]
By the way, you may better change your OpenAI API key now. I'm afraid that the public file might leak your key.

**Comment by StealthMeister1** [comment]
Oh wow. Well, I'm glad to have been able to work with you to fix it! The other guy that made a Villager AI mod never responded to my issues so that's when I came here and you responded damn near instantly lol.

**Comment by Ranzeplay** [comment]
I'm glad that I can help you! Although it cost you so much time.
Sorry for not solving it faster.

**Comment by StealthMeister1** [comment]
Maaaaan you're fine. I'm an admin IRL, so I understand stuff happens.

**Comment by Ranzeplay** [comment]
Okay, so we can finally close the issue happily?

**Comment by StealthMeister1** [comment]
Yes we can!
