### ISSUE TITLE
Use Villager's custom name if already set

### ISSUE THREAD

**Issue by HatTrkPatrk** [Ranzeplay/saysth#2]
For the `nameCandidates` part of the configuration, can it be setup such that it automatically uses the custom name of the villager if one is already set?

For example, while using the Villager Names mod from Serilum: https://modrinth.com/mod/villager-names-serilum

**Comment by Ranzeplay** [comment]
Okay, I'll implement the feature

**Comment by Ranzeplay** [comment]
Which game version do you use? I'll compile that version first.
