### ISSUE TITLE
Support for OpenAI and/or LM Studio

### ISSUE THREAD

**Issue by vico93** [Ranzeplay/saysth#6]
Basically, allow OpenAI (or LM Studio [running as a server in OpenAI-like API mode](https://lmstudio.ai/docs/basics/server)) as an alternate provider to Cloudflare AI.

**Comment by Ranzeplay** [comment]
I'm not familiar with LM Studio or OpenAI APIs, but I'll try to add them anyway.

**Comment by Ranzeplay** [comment]
I found that Cloudflare does support OpenAI-compatible API endpoints. Maybe we can make use of this and switch to OpenAI endpoints.

**Comment by Ranzeplay** [comment]
Okay, I've done the coding. After testing the code tonight, the branch feat#6 will be merged into master branch.

**Comment by vico93** [comment]
If you need more info about OpenAI stuff: https://platform.openai.com/docs/api-reference/introduction
