### ISSUE TITLE
Ability to use Villager entity data to feed the AI

### ISSUE THREAD

**Issue by vico93** [Ranzeplay/saysth#7]
Basically, Villagers [have lots of stuff](https://minecraft.wiki/w/Villager#Entity_data) inside their entity data that could be fed in some way into the AI to make the interactions more rich.

For example, based on the gossips level he could treat badly or good the player, talk dirty when willing to mate (lol), or just say trivias about their profession (depending of their level on that).

Also, if possible, you could send the offers information to the AI as well to make the villagers talk things related to their offer, eg. "I sell cod for a great price".

**Comment by Ranzeplay** [comment]
Indeed, some of the entity data had already been fed to the AI, such as profession and living environment. But difficulties remain. 
I considered the trade before, it was implemented in some early tests. But it didn't look good, so I removed this feature and added it back in future versions.
I still need more time to figure out how to write a nice prompt for villager entity data.

Here are some questions:
- Is it proper to pass villager trades into system messages?
- How to organize entity data well?

**Comment by vico93** [comment]
Good questions. I will try to answer with what i have of knowledge (not much, but i did a bot that used OpenAI API for Discord before):

1. I think one way to approach this (dont know if it would be the most efficient ngl) would be passing all the initial trades to the AI in the first time the mod sends the data (its done when the villager spawns in the world?) in the prompt template. Perharps creating a new variable called `{tradelist}`that expands to a "loop" containing all initial trades (eg: `"Your trades are: X coal for Y emeralds, X emeralds to Y cooked potatoes, etc"`. When the villager trades are updated, send a new system message updating the information.
2. This is a good question that i need to think about. One thing i noticed for my proposed `{tradelist}` is that a form of translation (or customizable formatting of the trade list) could be desirable, specially if the player would want the AI to talk in different languages other than English.

**Comment by Ranzeplay** [comment]
Thank you for your suggestions! I'll try.
